cookie:
  expiry_days: 30
  key: rapidrag_secret_key_2024
  name: rapidrag_auth
credentials:
  usernames:
    admin:
      name: Admin
      password: $2b$12$KIXq7zJ5F5QxZ5Z5Z5Z5ZO5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5
    demo:
      name: Demo User
      password: $2b$12$KIXq7zJ5F5QxZ5Z5Z5Z5ZO5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5
preauthorized: []
